name: Build huggingface Image

on:
  push:
    branches: [ hug ]
    paths:
      - 'Dockerfile'
      - 'index.js'
      - 'package.json'
      - 'index.html'
  pull_request:
    branches: [ hug ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: hug

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        env:
          OWNER: ${{ github.repository_owner }}
        run: |
          # 将用户名转成小写
          owner=$(echo "$OWNER" | tr '[:upper:]' '[:lower:]')
          
          # 构建并推送镜像
          docker buildx build \
            --push \
            --tag ghcr.io/${owner}/sdgssite:latest \
            --label org.opencontainers.image.source=https://github.com/${{ github.repository }} \
            --label org.opencontainers.image.description="http server" \
            --label org.opencontainers.image.licenses=MIT \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            .
